name: Test Runner
on:
  - push
jobs:
  Test-Runner:
    name: "Test Benchmarks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: yarn install
      - run: ./bin/run.sh
