name: Test Runner
on:
  - push
jobs:
  Test-Runner:
    name: "Test Benchmarks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: ./bin/run.sh
